# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run test:coverage
    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
    - name: Create the badge
      if: github.ref == 'refs/heads/main'
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
        gistID: 831eac19a71961961077dfb8d00f7224
        filename: jest-coverage-comment__main.json
        label: Coverage
        message: ${{ steps.coverageComment.outputs.coverage }}%
        color: ${{ steps.coverageComment.outputs.color }}
        namedLogo: jest
